apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
      - image: kukushka/simpe-server:latest
        name: simpleserver
        imagePullPolicy: Always 
        ports:
        - name: web
          containerPort: 5000
          protocol: TCP